import { AppCard } from './types';

// Sample app data
export const sampleApps: AppCard[] = [
  {
    id: '1',
    name: 'SolPay Mini',
    intro: 'Fast and secure payments on Solana',
    category: 'DeFi',
    tags: ['Payments', 'Wallet'],
    image: '/placeholder.svg',
    website: 'https://solpay.com',
    verified: true,
  },
  {
    id: '2',
    name: 'Orbit Dex',
    intro: 'Decentralized exchange for Solana tokens',
    category: 'DeFi',
    tags: ['DEX', 'Trading'],
    image: '/placeholder.svg',
    website: 'https://orbitdex.com',
    verified: true,
  },
  {
    id: '3',
    name: 'Nova Games',
    intro: 'Play-to-earn gaming platform',
    category: 'Games',
    tags: ['Gaming', 'NFT'],
    image: '/placeholder.svg',
    website: 'https://novagames.com',
    verified: false,
  },
  {
    id: '4',
    name: 'RippleChat',
    intro: 'Decentralized social messaging',
    category: 'Social',
    tags: ['Chat', 'Social'],
    image: '/placeholder.svg',
    website: 'https://ripplechat.com',
    verified: true,
  },
  {
    id: '5',
    name: 'Keystone Tools',
    intro: 'Developer tools for Solana',
    category: 'Tools',
    tags: ['Developer', 'Tools'],
    image: '/placeholder.svg',
    website: 'https://keystonetools.com',
    verified: true,
  },
  {
    id: '6',
    name: 'Yield Farm Pro',
    intro: 'Maximize your DeFi yields',
    category: 'DeFi',
    tags: ['Yield', 'Farming'],
    image: '/placeholder.svg',
    website: 'https://yieldfarmpro.com',
    verified: false,
  },
  {
    id: '7',
    name: 'Solana Social',
    intro: 'Social network on Solana',
    category: 'Social',
    tags: ['Social', 'Network'],
    image: '/placeholder.svg',
    website: 'https://solanasocial.com',
    verified: true,
  },
  {
    id: '8',
    name: 'Crypto Quest',
    intro: 'Adventure RPG with crypto rewards',
    category: 'Games',
    tags: ['RPG', 'Adventure'],
    image: '/placeholder.svg',
    website: 'https://cryptoquest.com',
    verified: false,
  },
];
